# Generated by Django 3.0.6 on 2020-05-21 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area_ikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_ikan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='gudang_ikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_masuk', models.DateField(auto_now_add=True)),
                ('juragan', models.CharField(max_length=50)),
                ('berat', models.IntegerField()),
                ('id_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminn.area_ikan')),
            ],
        ),
        migrations.CreateModel(
            name='harga_ikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_ikan', models.TextField()),
                ('harga_per_kg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('status', models.CharField(default='Aktif', max_length=20)),
                ('jabatan', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='penjualan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_penjualan', models.DateField(auto_now_add=True)),
                ('total_berat', models.IntegerField()),
                ('total_harga', models.IntegerField()),
                ('id_ikan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.gudang_ikan')),
            ],
        ),
        migrations.AddField(
            model_name='gudang_ikan',
            name='id_harga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.harga_ikan'),
        ),
    ]
